# base-workflows/.github/workflows/ci-pipeline.yml
name: CI Pipeline

on:
  workflow_call:
    secrets: inherit

jobs:
  lint-and-typecheck:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: community-of-python/community-workflow/.github/workflows/lint.yml@main
    secrets: inherit

  test-and-coverage:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: community-of-python/community-workflow/.github/workflows/test.yml@main
    secrets: inherit

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    uses: community-of-python/community-workflow/.github/workflows/publish.yml@main
    secrets: inherit