# base-workflows/.github/workflows/ci-pipeline.yml
name: CI Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true
      PYPI_TOKEN:
        required: true

jobs:
  lint:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: community-of-python/community-workflow/.github/workflows/lint.yml@2-add-uv-support
    with:
      python-version: ${{ inputs.python-version }}
    secrets: inherit

  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: community-of-python/community-workflow/.github/workflows/test.yml@2-add-uv-support
    with:
      python-version: ${{ inputs.python-version }}
    secrets: inherit

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    uses: community-of-python/community-workflow/.github/workflows/publish.yml@2-add-uv-support
    secrets: inherit
