# base-workflows/.github/workflows/ci-pipeline.yml
name: CI Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: false
        type: string
        default: '["ubuntu-latest","macos-latest","windows-latest"]'
jobs:
  lint:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: community-of-python/community-workflow/.github/workflows/lint.yml@main
    with:
      python-version: ${{ inputs.python-version }}
    secrets: inherit

  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: community-of-python/community-workflow/.github/workflows/test.yml@main
    with:
      python-version: ${{ inputs.python-version }}
      os: ${{ inputs.python-version }}
    secrets: inherit

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    uses: community-of-python/community-workflow/.github/workflows/publish.yml@main
    secrets: inherit
